### ISSUE TITLE
NPE when auto compile proto file

### ISSUE THREAD

**Issue by foresthuo** [google/protobuf-dt#20]
1. install protobuf-dt on spring tool suite
2. rename the attached tables.jpg to tables.zip and unzip it
3. open the tables workspace and you will see the project

NPE reported in Error View when compile to java file on saving the hello.proto file:

![tables](https://cloud.githubusercontent.com/assets/3608796/24642932/3893eeba-193d-11e7-833f-9193254671a3.jpg)

java.lang.NullPointerException
	at com.google.eclipse.protobuf.ui.protoc.command.ImportRootsProtocOption.locationAsFile(ImportRootsProtocOption.java:94)
	at com.google.eclipse.protobuf.ui.protoc.command.ImportRootsProtocOption.singleImportRoot(ImportRootsProtocOption.java:77)
	at com.google.eclipse.protobuf.ui.protoc.command.ImportRootsProtocOption.initialize(ImportRootsProtocOption.java:58)
	at com.google.eclipse.protobuf.ui.protoc.command.ImportRootsProtocOption.addOptionToCommand(ImportRootsProtocOption.java:42)
	at com.google.eclipse.protobuf.ui.protoc.command.ProtocCommandBuilder.buildCommand(ProtocCommandBuilder.java:51)
	at com.google.eclipse.protobuf.ui.builder.protoc.ProtobufBuildParticipant.build(ProtobufBuildParticipant.java:79)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by EnigmaGit** [comment]
I get the same error, or by tweaking my settings a similar but different error. See https://stackoverflow.com/questions/46603515/error-in-protobuf-dt

Did you ever work out how to fix this please?
